version: '3'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: juanpablopiano/nextjs:latest
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: npm run dev
